import type { Lead, LeadFilter } from "./types";

export const SMART_FILTERS: LeadFilter[] = [
  {
    id: "all",
    label: "Alle leads",
    description: "Vis hele porteføljen",
  },
  {
    id: "action-today",
    label: "Krever handling i dag",
    description: "Høy prioritet med nylig aktivitet",
  },
  {
    id: "ai-prioritized",
    label: "AI prioritert",
    description: "AI-score 70 eller høyere",
  },
  {
    id: "inactive",
    label: "Inaktive 7+ dager",
    description: "Leads uten kontakt siste uke",
  },
  {
    id: "new-inquiries",
    label: "Nye henvendelser",
    description: "Nye leads som venter på første kontakt",
  },
];

export const DEFAULT_LEADS: Lead[] = [
  {
    id: "lead-1",
    customerName: "Jennifer Walsh",
    email: "jennifer.walsh@email.no",
    phone: "+47 412 33 891",
    property: "Eikeveien 14, Oslo",
    propertyType: "Enebolig",
    status: "Tilbud sendt",
    stage: "hot",
    source: "Finn.no",
    lastActivity: "2t siden",
    lastActivityDays: 0,
    aiRecommendation: "Send personlig oppfølging på motbud innen kl. 12.",
    closingProbability: 78,
    aiPriorityScore: 94,
    priority: "Høy",
    budget: "8,5–9,2 mill",
    tags: ["Motbud", "Haster"],
  },
  {
    id: "lead-2",
    customerName: "Lisa & David Park",
    email: "park.family@gmail.com",
    phone: "+47 928 11 442",
    property: "Bjerkveien 8, Bærum",
    propertyType: "Tomannsbolig",
    status: "Motbud mottatt",
    stage: "hot",
    source: "Referanse",
    lastActivity: "5t siden",
    lastActivityDays: 0,
    aiRecommendation: "AI-utkast til svar er klart — gjennomgå og send.",
    closingProbability: 72,
    aiPriorityScore: 91,
    priority: "Høy",
    budget: "12–13 mill",
    tags: ["Motbud", "Familie"],
  },
  {
    id: "lead-3",
    customerName: "Anders & Kari Nilsen",
    email: "a.k.nilsen@outlook.com",
    phone: "+47 901 55 203",
    property: "Finn.no — Lillestrøm",
    propertyType: "Rekkehus",
    status: "Ny henvendelse",
    stage: "new",
    source: "Finn.no",
    lastActivity: "3t siden",
    lastActivityDays: 0,
    aiRecommendation: "Ring innen 30 min for høyest konvertering.",
    closingProbability: 22,
    aiPriorityScore: 88,
    priority: "Høy",
    budget: "5,5–6,2 mill",
    tags: ["Ny", "Førstegangskjøper"],
  },
  {
    id: "lead-4",
    customerName: "Michael Torres",
    email: "m.torres@firma.no",
    phone: "+47 977 44 128",
    property: "Maple Dr 42, Asker",
    propertyType: "Enebolig",
    status: "Visning booket",
    stage: "warm",
    source: "Hjemmeside",
    lastActivity: "18t siden",
    lastActivityDays: 1,
    aiRecommendation: "Bekreft visning og forbered prisargument.",
    closingProbability: 54,
    aiPriorityScore: 76,
    priority: "Medium",
    budget: "7–8 mill",
    tags: ["Visning", "Investor"],
  },
  {
    id: "lead-5",
    customerName: "Erik Johansen",
    email: "erik.j@live.no",
    phone: "+47 934 22 667",
    property: "Strandpromenaden 3, Drammen",
    propertyType: "Leilighet",
    status: "Under vurdering",
    stage: "active",
    source: "Zett",
    lastActivity: "1d siden",
    lastActivityDays: 1,
    aiRecommendation: "Del nylig solgt lignende objekt for å skape urgency.",
    closingProbability: 41,
    aiPriorityScore: 62,
    priority: "Medium",
    budget: "4,2–4,8 mill",
    tags: ["Sammenligning"],
  },
  {
    id: "lead-6",
    customerName: "Nina Berg",
    email: "nina.berg@email.no",
    phone: "+47 915 88 301",
    property: "Kirkegata 22, Trondheim",
    propertyType: "Leilighet",
    status: "Dialog pågår",
    stage: "active",
    source: "Finn.no",
    lastActivity: "2d siden",
    lastActivityDays: 2,
    aiRecommendation: "Planlegg oppfølgingssamtale denne uken.",
    closingProbability: 38,
    aiPriorityScore: 48,
    priority: "Lav",
    budget: "3,5–4 mill",
    tags: ["Oppfølging"],
  },
  {
    id: "lead-7",
    customerName: "Thomas & Marie Holm",
    email: "holm.couple@icloud.com",
    phone: "+47 988 33 774",
    property: "Skogveien 17, Stavanger",
    propertyType: "Enebolig",
    status: "Visning booket",
    stage: "warm",
    source: "Referanse",
    lastActivity: "4t siden",
    lastActivityDays: 0,
    aiRecommendation: "Send forberedelsesmail med nabolagsinfo før visning.",
    closingProbability: 61,
    aiPriorityScore: 82,
    priority: "Høy",
    budget: "9,5–10,5 mill",
    tags: ["Visning", "Premium"],
  },
  {
    id: "lead-8",
    customerName: "Sofia Lindqvist",
    email: "sofia.l@proton.me",
    phone: "+47 920 66 119",
    property: "Havnegata 5, Bergen",
    propertyType: "Leilighet",
    status: "Ny henvendelse",
    stage: "new",
    source: "Sosiale medier",
    lastActivity: "1t siden",
    lastActivityDays: 0,
    aiRecommendation: "Svar på Instagram-DM og book introduksjonssamtale.",
    closingProbability: 18,
    aiPriorityScore: 85,
    priority: "Høy",
    budget: "5–5,8 mill",
    tags: ["Ny", "Sosial"],
  },
  {
    id: "lead-9",
    customerName: "Henrik & Anna Svendsen",
    email: "svendsen.familie@online.no",
    phone: "+47 906 44 552",
    property: "Granlia 9, Sandvika",
    propertyType: "Rekkehus",
    status: "Tilbud sendt",
    stage: "hot",
    source: "Meglertjeneste",
    lastActivity: "8t siden",
    lastActivityDays: 0,
    aiRecommendation: "Følg opp tilbud — de vurderer konkurrerende objekt.",
    closingProbability: 69,
    aiPriorityScore: 79,
    priority: "Høy",
    budget: "6,8–7,5 mill",
    tags: ["Tilbud", "Konkurranse"],
  },
  {
    id: "lead-10",
    customerName: "Camilla Røstad",
    email: "camilla.rostad@firma.no",
    phone: "+47 913 77 228",
    property: "Parkveien 31, Kristiansand",
    propertyType: "Leilighet",
    status: "Dialog pågår",
    stage: "active",
    source: "Finn.no",
    lastActivity: "9d siden",
    lastActivityDays: 9,
    aiRecommendation: "Reaktiver med personlig markedsoppdatering — risiko for tap.",
    closingProbability: 29,
    aiPriorityScore: 71,
    priority: "Medium",
    budget: "3,8–4,2 mill",
    tags: ["Inaktiv", "Reaktivering"],
  },
  {
    id: "lead-11",
    customerName: "Jonas Meier",
    email: "j.meier@email.no",
    phone: "+47 995 12 884",
    property: "Fjordgata 2, Tromsø",
    propertyType: "Leilighet",
    status: "Under vurdering",
    stage: "active",
    source: "Zett",
    lastActivity: "12d siden",
    lastActivityDays: 12,
    aiRecommendation: "Send siste påminnelse før lead arkiveres automatisk.",
    closingProbability: 15,
    aiPriorityScore: 35,
    priority: "Lav",
    budget: "2,9–3,4 mill",
    tags: ["Inaktiv"],
  },
  {
    id: "lead-12",
    customerName: "Petra & Ole Haugen",
    email: "haugen.paret@gmail.com",
    phone: "+47 922 55 901",
    property: "Solheimsveien 44, Oslo",
    propertyType: "Tomannsbolig",
    status: "Ny henvendelse",
    stage: "new",
    source: "Hjemmeside",
    lastActivity: "45m siden",
    lastActivityDays: 0,
    aiRecommendation: "Ny lead fra kontaktskjema — ring nå mens interessen er høy.",
    closingProbability: 25,
    aiPriorityScore: 92,
    priority: "Høy",
    budget: "11–12 mill",
    tags: ["Ny", "Premium"],
  },
];
