import type { SettingsData } from "./types";

export const DEFAULT_SETTINGS_DATA: SettingsData = {
  company: {
    name: "Compass Realty Group",
    logoInitials: "CR",
    phone: "+47 22 44 55 66",
    email: "kontakt@compassrealty.no",
    address: "Karl Johans gate 14, 0154 Oslo",
    orgNumber: "912 345 678",
  },
  profile: {
    name: "Alex Rivera",
    role: "Senior eiendomsmegler",
    phone: "+47 412 88 990",
    email: "alex.rivera@compassrealty.no",
    language: "Norsk",
    avatarInitials: "AR",
  },
  ai: {
    aggressiveness: "moderat",
    tone: "profesjonell",
    automaticFollowups: true,
    automaticReminders: true,
    dailyBriefing: true,
    weeklyReport: true,
    confidenceThreshold: 75,
  },
  notifications: {
    email: true,
    sms: true,
    push: true,
    desktop: false,
    leadAlerts: true,
    highPriorityAlerts: true,
    meetingReminders: true,
  },
  integrations: [
    {
      id: "instagram",
      name: "Instagram",
      description: "Hent leads fra DM og kommentarer automatisk",
      connected: true,
      lastSync: "2 min siden",
      status: "aktiv",
    },
    {
      id: "manychat",
      name: "ManyChat",
      description: "Chatbot og automatisk leadfangst",
      connected: true,
      lastSync: "15 min siden",
      status: "aktiv",
    },
    {
      id: "make",
      name: "Make",
      description: "Automatiserte arbeidsflyter og integrasjoner",
      connected: false,
      lastSync: "Aldri",
      status: "ikke tilkoblet",
    },
    {
      id: "supabase",
      name: "Supabase",
      description: "Database, autentisering og sanntidsdata",
      connected: false,
      lastSync: "Aldri",
      status: "ikke tilkoblet",
    },
    {
      id: "google-calendar",
      name: "Google Calendar",
      description: "Synkroniser visninger og møter",
      connected: true,
      lastSync: "5 min siden",
      status: "aktiv",
    },
    {
      id: "outlook",
      name: "Microsoft Outlook",
      description: "E-post og kalenderintegrasjon",
      connected: false,
      lastSync: "Aldri",
      status: "ikke tilkoblet",
    },
  ],
  security: {
    twoFactorEnabled: true,
    activeSessions: 2,
    activeDevices: ["MacBook Pro — Oslo", "iPhone 15 — Oslo"],
    lastLogin: "I dag, 08:14",
    lastLoginLocation: "Oslo, Norge",
  },
  subscription: {
    name: "VerdiFlow Enterprise",
    price: "2 490 kr / mnd",
    nextPayment: "1. april 2026",
    features: [
      "Ubegrenset AI-assistent",
      "Avansert pipeline og analytics",
      "Automatiske oppfølginger",
      "Integrasjoner (Instagram, Calendar)",
      "Prioritert support",
    ],
  },
};
