import {
  Bot,
  Clock,
  FileCheck,
  MessageSquare,
  Share2,
  Timer,
  TrendingUp,
  Zap,
} from "lucide-react";

import type { AnalyticsData } from "./types";

const CHART_LABELS = [
  "1. mar", "5. mar", "9. mar", "13. mar", "17. mar", "21. mar", "25. mar", "29. mar",
];

export const DEFAULT_ANALYTICS_DATA: AnalyticsData = {
  topKpis: [
    {
      id: "pipeline-value",
      label: "Pipeline-verdi",
      value: 32.4,
      suffix: "M kr",
      decimals: 1,
      trend: { value: "+18%", positive: true },
      sparkline: [22, 24, 25, 27, 28, 30, 32.4],
      icon: "trending-up",
    },
    {
      id: "conversion-rate",
      label: "Konverteringsrate",
      value: 34,
      suffix: "%",
      trend: { value: "+5%", positive: true },
      sparkline: [26, 27, 28, 30, 31, 32, 34],
      icon: "percent",
    },
    {
      id: "monthly-revenue",
      label: "Omsetning denne måneden",
      value: 4.2,
      suffix: "M kr",
      decimals: 1,
      trend: { value: "+12%", positive: true },
      sparkline: [2.8, 3.1, 3.0, 3.4, 3.6, 3.9, 4.2],
      icon: "banknote",
    },
    {
      id: "ai-time-saved",
      label: "Tid spart av AI",
      value: 19,
      suffix: "t",
      trend: { value: "+4t", positive: true },
      sparkline: [10, 12, 13, 14, 16, 17, 19],
      icon: "clock",
    },
  ],
  salesChart: {
    labels: CHART_LABELS,
    series: [
      {
        id: "pipeline",
        label: "Pipeline-vekst",
        color: "rgba(52,211,153,0.85)",
        data: [18, 20, 22, 24, 26, 28, 30, 32],
      },
      {
        id: "deals",
        label: "Lukkede avtaler",
        color: "rgba(96,165,250,0.75)",
        data: [2, 3, 2, 4, 3, 5, 4, 6],
      },
      {
        id: "leads",
        label: "Nye leads",
        color: "rgba(251,191,36,0.7)",
        data: [8, 10, 9, 12, 11, 14, 13, 15],
      },
    ],
  },
  leadSources: [
    { id: "finn", label: "Finn.no", percentage: 38, count: 46, color: "bg-emerald-400" },
    { id: "instagram", label: "Instagram", percentage: 28, count: 34, color: "bg-violet-400" },
    { id: "referanser", label: "Referanser", percentage: 18, count: 22, color: "bg-sky-400" },
    { id: "hjemmeside", label: "Hjemmeside", percentage: 11, count: 13, color: "bg-amber-400" },
    { id: "andre", label: "Andre", percentage: 5, count: 6, color: "bg-zinc-500" },
  ],
  aiPerformance: [
    {
      id: "followups",
      label: "Oppfølginger generert",
      value: "142",
      trend: { value: "+28%", positive: true },
      icon: MessageSquare,
    },
    {
      id: "time-saved",
      label: "Tid spart",
      value: "19t",
      trend: { value: "+4t", positive: true },
      icon: Clock,
    },
    {
      id: "drafts-approved",
      label: "AI-utkast godkjent",
      value: "87%",
      trend: { value: "+6%", positive: true },
      icon: FileCheck,
    },
    {
      id: "automations",
      label: "Automatiseringer kjørt",
      value: "312",
      trend: { value: "+22%", positive: true },
      icon: Zap,
    },
    {
      id: "response-time",
      label: "Gjennomsnittlig svartid",
      value: "12 min",
      trend: { value: "-34%", positive: true },
      icon: Timer,
    },
  ],
  agentLeaderboard: [
    {
      id: "agent-1",
      name: "Alex Rivera",
      closedDeals: 8,
      pipelineValue: "12,4M kr",
      conversionRate: 38,
      aiScore: 94,
      isTopPerformer: true,
    },
    {
      id: "agent-2",
      name: "Sofia Berg",
      closedDeals: 6,
      pipelineValue: "9,8M kr",
      conversionRate: 34,
      aiScore: 89,
    },
    {
      id: "agent-3",
      name: "Erik Nilsen",
      closedDeals: 5,
      pipelineValue: "7,2M kr",
      conversionRate: 31,
      aiScore: 82,
    },
    {
      id: "agent-4",
      name: "Maria Holm",
      closedDeals: 4,
      pipelineValue: "5,6M kr",
      conversionRate: 28,
      aiScore: 78,
    },
    {
      id: "agent-5",
      name: "Jonas Meier",
      closedDeals: 3,
      pipelineValue: "4,1M kr",
      conversionRate: 24,
      aiScore: 71,
    },
  ],
  weeklyInsights: [
    {
      id: "insight-1",
      title: "Instagram gir nå 28% flere varme leads.",
      recommendation: "Øk budsjett for sosiale kampanjer med 15% neste uke.",
      confidence: 91,
      icon: Share2,
    },
    {
      id: "insight-2",
      title: "Responstid falt med 34%.",
      recommendation: "Behold AI-automatisering for første kontakt på nye leads.",
      confidence: 94,
      icon: Timer,
    },
    {
      id: "insight-3",
      title: "Pipeline økte med 18%.",
      recommendation: "Fokuser på forhandlingsfasen — 4 leads nær lukking.",
      confidence: 87,
      icon: TrendingUp,
    },
    {
      id: "insight-4",
      title: "AI sparte totalt 19 timer denne uken.",
      recommendation: "Gjennomgå 6 ventende AI-utkast for raskere oppfølging.",
      confidence: 96,
      icon: Bot,
    },
  ],
  forecast: {
    expectedPipeline: "38,5M kr",
    expectedClosedDeals: 9,
    expectedRevenue: "5,1M kr",
    confidence: 82,
    recommendedActions: [
      "Prioriter 3 hot leads i forhandlingsfasen for å nå omsetningsmål",
      "Øk oppfølging på Finn.no-leads — høyest konvertering siste 30 dager",
      "Book 2 ekstra visninger i premium-segmentet (9,5M+)",
      "Aktiver reaktiveringskampanje for 4 inaktive leads",
    ],
  },
};
